
apiVersion: v1
kind: Namespace
metadata:
  name: storage
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: storage
spec:
  ports:
  - targetPort: 9200
    port: 9200
    name: opensearch
  selector:
    app: opensearch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch
  namespace: storage
spec:
  selector:
    matchLabels:
      app: opensearch
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
      - image: opensearchproject/opensearch:1.3.9
        name: opensearch
        env:
          - name: discovery.type
            value: 'single-node'
